API_key: "c26ead3d4b5b4b8381c185109240306" # Provide your (free) API key from your account at https://www.weatherapi.com/
city: "Uppsala" # City to fetch weather from
update_interval: 6000 # Update interval in ticks. Default is 6000 (5 min)