name: ActualWeather
version: '1.0'
main: com.actualweather.actualweather.ActualWeather
api-version: '1.20'
description: A plugin to sync Minecraft weather with real-world weather.
commands:
  actualweather:
    usage: /<command>
    description: Administrate the Actualweather plugin.
  aw:
    usage: /<command>
    description: Administrate the Actualweather plugin.