name: ActualWeather
version: '${project.version}'
main: com.actualweather.actualweather.ActualWeather
api-version: '1.20'
description: A plugin to sync Minecraft weather with real-world weather.
author: HellRemus
commands:
  actualweather:
    description: Administrate the Actualweather plugin.
    usage: /<command>
  aw:
    description: Administrate the Actualweather plugin.
    usage: /<command>